# Coded by: Sp1dermanhacker
# Youtube: https://www.youtube.com/channel/UCwL-qGwm5ncO6IfB83x35BA?view_as=subscriber
# Github: https://github.com/sp1dermanhackeryoutube

answer = input("Will you use this for educational purposes only? Y/N: ")
answers = "Y"
answerss = "y"
print("")
if answer==answers or answer==answerss:
    print("  _____      __     _             _______          _                                                                     ")
    print(" / ____|    /_ |   | |           |__   __|        | |                                                                    ")
    print("| (___  _ __ | | __| | ___ _ __     | | ___   ___ | |___                                                                 ")
    print(" \___ \| '_ \| |/_` |/ _ \ '__|     | |/ _ \ / _ \| / __|                                                                ")
    print("____) | |_)  | | (_| |  __/ |       | | (_) | (_) | \__ \                                                                ")
    print("|_____/| .__/|_|\__,_|\___|_|       |_|\___/ \___/|_|___/                                                                ")
    print("       | |                                                                                                               ")
    print("       |_|                                                                                                               ")
    print("       |_|                                                                                                               ")
else:
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y")
    print("You didn't say Y") + quit()
    
print("[1] Password list generator")
print("[2] Phishing")
choose = input("Choose a number: ")
number = "1"
num2 = "2"
print("")
if choose==number:
    
    import os
    os.system("clear")
    name = input("Enter target first name: ")
    lastname = input("Enter target last name: ")
    birthday = input("Enter target birthday (DDMMYYYY): ")
    year = input("Enter target year: ")
    friend = input("Enter target friend: ")
    partner = input("Enter target partner: ")
    parent = input("Enter one of the parents first name: ")
    parent2 = input("Enter another one of the parents first name: ")
    sibling = input("Enter a siblings first name: ")
    sibling2 = input("Enter another siblings first name: ")
    company = input("Enter target School/Work/Company: ")
    country = input("Enter target country: ")
    city = input("Enter target city: ")
    words = input("Enter ONE keyword: ")
    words2 = input("Enter ONE more keyword: ")
    words3 = input("Enter ONE more keyword: ")
    words4 = input("Enter ONE more keyword: ")
    words5 = input("Enter ONE more keyword: ")
    words6 = input("Enter ONE more keyword: ")
    words7 = input("Enter ONE more keyword: ")
    words8 = input("Enter ONE more keyword: ")
    words9 = input("Enter ONE more keyword: ")
    
    os.system("clear") 
    print("Copy these passwords into a password list: ")
    
    print(name)
    print(name + "123")
    print(name + "1234")
    print(name + "12345")
    print(name + "123456")
    print(name + "1234567")
    print(name + "12345678")
    print(name + birthday)
    print(name + year)
    print(name + city)
    print(name + country)
    print(name + lastname)
    print(name + lastname + birthday)
    print(name + lastname + year)
    print(name + company)
    print(name + words)
    print(name + words2)
    print(name + words3)
    print(name + words4)
    print(name + words5)
    print(name + words6)
    print(name + words7)
    print(name + words8)
    print(name + words9)
    print(name + city)
    print(name + country)
    print(lastname)
    print(lastname + words)
    print(lastname + words2)
    print(lastname + words3)
    print(lastname + words4)
    print(lastname + words5)
    print(lastname + words6)
    print(lastname + words7)
    print(lastname + words8)
    print(lastname + words9)
    print(lastname + "123")
    print(lastname + "1234")
    print(lastname + "12345")
    print(lastname + "123456")
    print(lastname + "1234567")
    print(lastname + "12345678")
    print(lastname + name)
    print(lastname + birthday)
    print(lastname + year)
    print(lastname + name)
    print(lastname + name + birthday)
    print(lastname + name + year)
    print(birthday)
    print(birthday + name)
    print(birthday + lastname)
    print(birthday + company)
    print(year)
    print(year + name)
    print(year + lastname)
    print(year + words)
    print(year + words2)
    print(year + words3)
    print(year + words4)
    print(year + words5)
    print(year + words6)
    print(year + words7)
    print(year + words8)
    print(year + words9)
    print(year + city)
    print(year + country)
    print(words)
    print(words + "12345")
    print(words + "123456")
    print(words + "12345678")
    print(words + "1234")
    print(words + "123")
    print(words + "1234567")
    print(words + name)
    print(words + company)
    print(words + lastname)
    print(words + city)
    print(words + country)
    print(words + sibling)
    print(words + sibling2)
    print(words + parent)
    print(words + parent2)
    print(words + partner)
    print(words + friend)
    print(words + year)
    print(words + birthday)
    print(words + lastname)
    print(words2)
    print(words2 + "12345")
    print(words2 + "123456")
    print(words2 + "12345678")
    print(words2 + "1234")
    print(words2 + "123")
    print(words2 + "1234567")
    print(words2 + name)
    print(words2 + company)
    print(words2 + lastname)
    print(words2 + city)
    print(words2 + country)
    print(words2 + sibling)
    print(words2 + sibling2)
    print(words2 + parent)
    print(words2 + parent2)
    print(words2 + partner)
    print(words2 + friend)
    print(words2 + year)
    print(words2 + birthday)
    print(words2 + lastname)
    print(words3)
    print(words3 + "12345")
    print(words3 + "123456")
    print(words3 + "12345678")
    print(words3 + "1234")
    print(words3 + "123")
    print(words3 + "1234567")
    print(words3 + name)
    print(words3 + company)
    print(words3 + lastname)
    print(words3 + city)
    print(words3 + country)
    print(words3 + sibling)
    print(words3 + sibling2)
    print(words3 + parent)
    print(words3 + parent2)
    print(words3 + partner)
    print(words3 + friend)
    print(words3 + year)
    print(words3 + birthday)
    print(words3 + lastname)
    print(words4)
    print(words4 + "12345")
    print(words4 + "123456")
    print(words4 + "12345678")
    print(words4 + "1234")
    print(words4 + "123")
    print(words4 + "1234567")
    print(words4 + name)
    print(words4 + company)
    print(words4 + lastname)
    print(words4 + city)
    print(words4 + country)
    print(words4 + sibling)
    print(words4 + sibling2)
    print(words4 + parent)
    print(words4 + parent2)
    print(words4 + partner)
    print(words4 + friend)
    print(words4 + year)
    print(words4 + birthday)
    print(words4 + lastname)
    print(words5)
    print(words5 + "12345")
    print(words5 + "123456")
    print(words5 + "12345678")
    print(words5 + "1234")
    print(words5 + "123")
    print(words5 + "1234567")
    print(words5 + name)
    print(words5 + company)
    print(words5 + lastname)
    print(words5 + city)
    print(words5 + country)
    print(words5 + sibling)
    print(words5 + sibling2)
    print(words5 + parent)
    print(words5 + parent2)
    print(words5 + partner)
    print(words5 + friend)
    print(words5 + year)
    print(words5 + birthday)
    print(words5 + lastname)
    print(words6)
    print(words6 + "12345")
    print(words6 + "123456")
    print(words6 + "12345678")
    print(words6 + "1234")
    print(words6 + "123")
    print(words6 + "1234567")
    print(words6 + name)
    print(words6 + company)
    print(words6 + lastname)
    print(words6 + city)
    print(words6 + country)
    print(words6 + sibling)
    print(words6 + sibling2)
    print(words6 + parent)
    print(words6 + parent2)
    print(words6 + partner)
    print(words6 + friend)
    print(words6 + year)
    print(words6 + birthday)
    print(words6 + lastname)
    print(words7 + "12345")
    print(words7 + "123456")
    print(words7 + "12345678")
    print(words7 + "1234")
    print(words7 + "123")
    print(words7 + "1234567")
    print(words7)
    print(words7 + name)
    print(words7 + company)
    print(words7 + lastname)
    print(words7 + city)
    print(words7 + country)
    print(words7 + sibling)
    print(words7 + sibling2)
    print(words7 + parent)
    print(words7 + parent2)
    print(words7 + partner)
    print(words7 + friend)
    print(words7 + year)
    print(words7 + birthday)
    print(words7 + lastname)
    print(words8)
    print(words8 + "123")
    print(words8 + "123456")
    print(words8 + "12345")
    print(words8 + "1234")
    print(words8 + "12345678")
    print(words8 + "1234567")
    print(words8 + name)
    print(words8 + company)
    print(words8 + lastname)
    print(words8 + city)
    print(words8 + country)
    print(words8 + sibling)
    print(words8 + sibling2)
    print(words8 + parent)
    print(words8 + parent2)
    print(words8 + partner)
    print(words8 + friend)
    print(words8 + year)
    print(words8 + birthday)
    print(words8 + lastname)
    print(words9)
    print(words9 + name)
    print(words9 + company)
    print(words9 + lastname)
    print(words9 + city)
    print(words9 + country)
    print(words9 + sibling)
    print(words9 + sibling2)
    print(words9 + parent)
    print(words9 + parent2)
    print(words9 + partner)
    print(words9 + friend)
    print(words9 + year)
    print(words9 + birthday)
    print(words9 + lastname)
    print("password")
    print("iloveyou")
    print("12345")
    print("123456")
    print("12345678")
    print(city)
    print(city + name)
    print(city + lastname)
    print(city + country)
    print(city + partner)
    print(city + year)
    print(city + birthday)
    print(city + parent)
    print(city + parent2)
    print(city + sibling)
    print(city + sibling2)
    print(city + words)
    print(city + words2)
    print(city + words3)
    print(city + words4)
    print(city + words5)
    print(city + words6)
    print(city + words7)
    print(city + words8)
    print(city + words9)
    print("admin")
    print("user")
    print("username")
    
if choose==num2:
    print(" _____  _     _     _     _                                                                            ")
    print("|  __ \| |   (_)   | |   (_)                                                                            ")
    print("| |__) | |__  _ ___| |__  _ _ __   __ _                                                                 ")
    print("|  ___/| '_ \| / __| '_ \| | '_ \ / _` |                                                                ")
    print("| |    | | | | \__ \ | | | | | | | (_| |                                                                ")
    print("|_|    |_| |_|_|___/_| |_|_|_| |_|\__, |                                                                ")
    print("                                   __/ |                                                                ")
    print("                                  |___/                                                                 ")
    
    starting = input("Do you want to start? y/n: ")
    startings = "y"
    startingss = "Y"
    print("")
    if starting==startings or starting==startingss:
        import sendgrid
        import os
        from sendgrid.helpers.mail import *
        
        def sendPhish(FROM, TO, subject, content):
            sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
            from_email = Email(FROM)
            to_email = Email(TO)
            subject = subject
            content = Content("text/plain", content)
            mail = Mail(from_email, subject, to_email, content)
            response = sg.client.mail.send.post(request_body=mail.get())
            print(response.status_code)
            print(response.body)
            print(response.headers)
        
        sendPhish("youremail@mail.com", "sp1dermanhackerisgood@gmail.com", "Hello", "Test")
    else:
        quit()
else:
    print("Error") + quit()
        
 
    
    
    
